### PR TITLE
Changing name of services

### PR DESCRIPTION
**Pull request by lube**
Chaning name of the services, preprending them the vendor name so it does not conflict with other vendors that use json_schema.*

### CODE REVIEW

**Comment by HadesArchitect** [comment]
Hi Sebastian, and thank you for a PR!
1. Sadly you included your composer.json into the PR and if I will accept it, it will override my composer.json which is not right. May you remove your composer.json from the PR?
2. The tests are broken, but it's not your issue - I have to update them.

**Comment by HadesArchitect** [comment]
I've just updated tests, please merge master branch into yours. Then the tests for this MR also should work.

**Comment by lube** [comment]
Done! Thanks for the merge!

**Comment by lube** [comment]
@HadesArchitect any news on this?

**Comment by HadesArchitect** [comment]
Well done, thank you!

Probably later I'll rename it to have same 'vendor name' here & in the notification bundle.

**Pull request merged**
